from django.db import models

# Create your models here.
class CurrencyRecord(models.Model):
    date = models.DateField(primary_key=True)
    DZD = models.FloatField(null=True, default=None)
    AUD = models.FloatField(null=True, default=None)
    BHD = models.FloatField(null=True, default=None)
    VEF = models.FloatField(null=True, default=None)
    BWP = models.FloatField(null=True, default=None)
    BRL = models.FloatField(null=True, default=None)
    BND = models.FloatField(null=True, default=None)
    CAD = models.FloatField(null=True, default=None)
    CLP = models.FloatField(null=True, default=None)
    CNY = models.FloatField(null=True, default=None)
    COP = models.FloatField(null=True, default=None)
    CZK = models.FloatField(null=True, default=None)
    DKK = models.FloatField(null=True, default=None)
    EUR = models.FloatField(null=True, default=None)
    HUF = models.FloatField(null=True, default=None)
    ISK = models.FloatField(null=True, default=None)
    INR = models.FloatField(null=True, default=None)
    IDR = models.FloatField(null=True, default=None)
    IRR = models.FloatField(null=True, default=None)
    ILS = models.FloatField(null=True, default=None)
    JPY = models.FloatField(null=True, default=None)
    KZT = models.FloatField(null=True, default=None)
    KRW = models.FloatField(null=True, default=None)
    KWD = models.FloatField(null=True, default=None)
    LYD = models.FloatField(null=True, default=None)
    MYR = models.FloatField(null=True, default=None)
    MUR = models.FloatField(null=True, default=None)
    MXN = models.FloatField(null=True, default=None)
    NPR = models.FloatField(null=True, default=None)
    NZD = models.FloatField(null=True, default=None)
    NOK = models.FloatField(null=True, default=None)
    OMR = models.FloatField(null=True, default=None)
    PKR = models.FloatField(null=True, default=None)
    PEN = models.FloatField(null=True, default=None)
    PHP = models.FloatField(null=True, default=None)
    PLN = models.FloatField(null=True, default=None)
    QAR = models.FloatField(null=True, default=None)
    RUB = models.FloatField(null=True, default=None)
    SAR = models.FloatField(null=True, default=None)
    SGD = models.FloatField(null=True, default=None)
    ZAR = models.FloatField(null=True, default=None)
    LKR = models.FloatField(null=True, default=None)
    SEK = models.FloatField(null=True, default=None)
    CHF = models.FloatField(null=True, default=None)
    THB = models.FloatField(null=True, default=None)
    TTD = models.FloatField(null=True, default=None)
    TND = models.FloatField(null=True, default=None)
    AED = models.FloatField(null=True, default=None)
    GBP = models.FloatField(null=True, default=None)
    USD = models.FloatField(null=False, blank=False, default=1)
    UYU = models.FloatField(null=True, default=None)

