# Generated by Django 3.2.15 on 2022-09-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRecord',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('inr', models.FloatField()),
                ('usd', models.FloatField(default=1)),
            ],
        ),
    ]
