# Generated by Django 3.2.15 on 2022-09-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyrecord',
            old_name='usd',
            new_name='USD',
        ),
        migrations.RemoveField(
            model_name='currencyrecord',
            name='inr',
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='AED',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='AUD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='BHD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='BND',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='BRL',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='BWP',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='CAD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='CHF',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='CLP',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='CNY',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='COP',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='CZK',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='DKK',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='DZD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='EUR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='GBP',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='HUF',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='IDR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='ILS',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='INR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='IRR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='ISK',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='JPY',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='KRW',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='KWD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='KZT',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='LKR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='LYD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='MUR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='MXN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='MYR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='NOK',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='NPR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='NZD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='OMR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='PEN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='PHP',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='PKR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='PLN',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='QAR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='RUB',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='SAR',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='SEK',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='SGD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='THB',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='TND',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='TTD',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='UYU',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='VEF',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='currencyrecord',
            name='ZAR',
            field=models.FloatField(default=None, null=True),
        ),
    ]
