# Generated by Django 3.2.15 on 2022-09-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220928_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrecord',
            name='VES',
            field=models.FloatField(default=None, null=True),
        ),
    ]
